### ISSUE TITLE
Cannot stream viewport

### ISSUE THREAD

**Issue by rtasan** [shycats/VirtuCameraBlender#9] opened 2021-09-08 15:30 UTC
Hi
When I tap the eye icon in iPad app to stream viewport, the plugin crashes and stop working
If I don't touch it, everything else works fine

Software: Blender 2.93.4
Scene: Default cube setup
Plugin version: VirtuCameraBlender-cp39-windows-x64-v1.1.0.zip

Here is the console

`VirtuCamera: Starting Viewport Capture. 60.00 fps, 2.00 Mbits/s, Opaque: 1, Autosend: 1
Traceback (most recent call last):
  File "C:\Users\Reiko\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\virtucamera_blender\virtucamera_blender.py", line 862, in timer_function
    vcserver.execute_pending_events()
  File "vc_core.pyx", line 1007, in virtucamera.vc_core.VCServer.execute_pending_events
  File "vc_core.pyx", line 1795, in virtucamera.vc_core.VCServer._start_streaming
  File "vc_core.pyx", line 1583, in virtucamera.vc_core.VCServer._start_encoding
  File "vc_core.pyx", line 1537, in virtucamera.vc_core.VCServer._start_subprocess
  File "vc_core.pyx", line 1520, in virtucamera.vc_core.VCServer._get_environment
TypeError: can only concatenate list (not "str") to list`

**Comment by shycats** [comment] 2021-09-09 07:32
Hi,

Thanks for reporting this, I will try to reproduce the problem and let you know as soon as I fix it.

**Comment by shycats** [comment] 2021-09-09 18:40
@rtasan Hey, I've tried on Windows 10 with Blender 2.93.4 but I'm unable to reproduce your error.
Is it possible that you are using a custom Blender build, with a custom Python version? Or maybe Windows 11?

Other explanation could be that another plug-in is modifying sys.path in a non conventional way. Maybe try by disabling all third-party plug-ins.

**Comment by rtasan** [comment] 2021-09-10 01:20
I identified the plugin that was causing the problem and fixed the code.
Now both work fine.
Thank you for your help.

**Comment by shycats** [comment] 2021-09-10 09:30
Awesome! closing ticket.

**Closed by shycats** 2021-09-10 09:30 UTC
